export enum MenuItemType {
  TEXT = 'TEXT',
  SPRITE = 'SPRITE',
  SPRITE_GROUP = 'SPRITE_GROUP',
  BUTTON = 'BUTTON',
  BUTTON_GROUP = 'BUTTON_GROUP',
  SCROLLABLE_TEXT = 'SCROLLABLE_TEXT',
  CHARACTER_SELECTOR = 'CHARACTER_SELECTOR',
  CHARACTER_SELECTOR_GROUP = 'CHARACTER_SELECTOR_GROUP'
}

export type MenuItemTypeValue = `${MenuItemType}`;
