export enum MenuItemType {
  TEXT = 'TEXT',
  SPRITE = 'SPRITE',
  SPRITE_GROUP = 'SPRITE_GROUP',
  BUTTON = 'BUTTON',
  BUTTON_GROUP = 'BUTTON_GROUP',
  SCROLLABLE_TEXT = 'SCROLLABLE_TEXT',
  CHARACTER_SELECTOR = 'CHARACTER_SELECTOR',
  CHARACTER_SELECTOR_GROUP = 'CHARACTER_SELECTOR_GROUP',
  SETTING = 'SETTING',
  KEY_BINDING_SETTING = 'KEY_BINDING_SETTING',
  TOGGLE_SETTING = 'TOGGLE_SETTING',
  SLIDER_SETTING = 'SLIDER_SETTING'
}

export type MenuItemTypeValue = `${MenuItemType}`;
