import { RIGHT } from 'phaser';
import { Language } from '../../enums/Language';

export const languageFiles = {
  [Language.ENGLISH]: {
    gameTitle: 'Tubie-Man',
    gameOver: 'GAME OVER',
    clickToRestart: 'Click to Restart',
    selectDifficulty: 'Difficulty:',
    easy: 'EASY',
    medium: 'MEDIUM',
    hard: 'HARD',
    controls: 'Controls: Arrow Keys or WASD\nFire: SPACE\nTouch: Swipe direction',
    score: 'Score',
    highScore: 'Record',
    lives: 'Lives',
    level: 'Level',
    power: 'PowerUp',
    powerReady: 'Ready ',
    powerNone: 'None',
    powerActive: 'Active',
    paused: 'PAUSED',
    continue: 'CONTINUE',
    quit: 'QUIT',
    menuPlay: 'PLAY',
    menuSettings: 'SETTINGS',
    menuAbout: 'ABOUT',
    menuInstructions: 'INSTRUCTIONS',
    menuBack: 'BACK',
    language: 'Language:',
    aboutSection: '\n[color=#FF6E31]Tubie Man[/color] wasn’t always trapped in a maze. A routine feeding-system calibration went spectacularly wrong, overloading a prototype power adapter and tearing a hole in the grid itself. Out rolled Tubie Man—bright orange, endlessly determined, and uniquely equipped with both an NG-tube and a G-tube to keep him going no matter what the maze throws at him.\n\nUnfortunately, [b]the maze isn’t empty[/b].\n\nFour anthropomorphic syringes now roam its corridors, each with their own idea of “[i]proper care[/i].”\n\n[color=#DE373A]Stingy[/color], the red enforcer, is fast, aggressive, and always closing in.\n\n[color=#55D400]Pokey[/color], green and persistent, means well but tends to get distracted—sometimes looping endlessly in circles.\n\n[color=#099EDE]Pricky[/color], a cerulean blue bundle of nerves, tries to chase but often forgets what he’s doing and wanders off instead.\n\nAnd [color=#FFB851]Doc[/color], orange like Tubie Man himself, appears only in the deeper levels, slowing down to think, stopping entirely, and then changing course when he decides he has a better plan.\n\nScattered throughout the maze are [b]nutrient pellets[/b] — tiny energy boosts Tubie Man must collect to survive. When he grabs one of the power-up band-aids tucked into the corners, things get intense. A sudden bout of catastrophic heartburn gives Tubie Man the ability to shoot fireballs for a short time, sending the syringes running for cover until the effect wears off. Pricky, especially terrified, may panic so badly he crashes into walls and stuns himself.\n\nAs the maze empties and most of the nutrients are gone, danger escalates. Stingy enters [b]Sterilization Mode[/b] — moving even faster and becoming completely immune to fireballs. Pokey grows more erratic. Pricky grows more [b]confused[/b]. Doc... keeps thinking...\n\n[size=18]Now Tubie Man races the clock, the maze, and his pursuers—proving he’s more than a patient. He’s a survivor. He’s a problem. And he’s not done yet.[/size]',
    instructionsSection: '\n[color=orange][size=18][b]Movement[/b][/size][/color]\n- Use [b][i]WASD[/b][/i], [b][i]arrow keys[/b][/i], or the [b][i]left stick[/b][/i] on a controller to move.\n\n[color=orange][size=18][b]Menus[/b][/size][/color]\n- Press [b][i]Enter[/b][/i] or [b][i]Space[/b][/i] to select a menu button.\n- Use [b][i]WASD[/b][/i], [b][i]arrow keys[/b][/i], [b][i]Tab, or the [b][i]left stick[/b][/i] to navigate menus.\n\n[color=orange][size=18][b]Pause[/b][/size][/color]\n- Press [b][i]Escape[/b][/i] (keyboard) or [b][i]Select/Share[/b][/i] (controller) to pause the game.\n\n[color=orange][size=18][b]Actions[/b][/size][/color]\n- Press [b][i]Space[/b][/i] (keyboard) or [b][i]A/X[/b][/i] (controller) to breathe fireballs.\n\n[color=orange][size=18][b]Scoring & Power-Ups[/b][/size][/color]\n- Collect nutrient pellets to score points.\n- Collect up to two bonuses per level for extra points.\n- Defeat enemies while powered up to earn points.\n- Eat the power-up in the corner to gain the ability to breathe fire.',
    helloWorld: 'Hello World',
    menuHighScores: 'HIGH SCORES',
    newHighScore: 'NEW HIGH SCORE!',
    enterName: 'Enter Your Name:',
    save: 'SAVE',
    rank: 'RANK',
    name: 'NAME',
    noScores: 'No scores yet!',
    playAgain: 'PLAY AGAIN',
    viewScores: 'VIEW SCORES',
    settingFire: 'Fire',
    settingContinue: 'Continue',
    settingPause: 'Pause',
    settingUp: 'Up',
    settingDown: 'Down',
    settingLeft: 'Left',
    settingRight: 'Right',
    settingArcadeMode: 'Arcade Mode',
    on: 'ON',
    off: 'OFF',
    tabGameplay: 'GAMEPLAY',
    tabKeyboard: 'KEYBOARD',
    tabController: 'CONTROLLER',
    getReady: 'Get Ready!',
    settingMasterVolume: 'Volume',
    settingMute: 'Mute ALl',
    settingsSfxMute: 'Mute Sounds',
    settingsMusicMute: 'Mute Music',
    settingMuteKey: 'Mute Key',
    isRightHanded: 'Touch Layout',
    rightHanded: 'Right',
    leftHanded: 'Left',
    copyright: '©Tubie Tech 2026, All Rights Reserved'
  },
  [Language.SPANISH]: {
    gameTitle: 'Hombre Tubía',
    gameOver: 'JUEGO TERMINADO',
    clickToRestart: 'Clic para Reiniciar',
    selectDifficulty: 'Dificultad:',
    easy: 'FÁCIL',
    medium: 'MEDIO',
    hard: 'DIFÍCIL',
    controls: 'Controles: Flechas o WASD\nFuego: ESPACIO\nTáctil: Deslizar dirección',
    score: 'Puntos',
    highScore: 'Récord',
    lives: 'Vidas',
    level: 'Nivel',
    power: 'Poder',
    powerReady: 'Listo ',
    powerNone: 'Ninguno',
    powerActive: 'Activo',
    paused: 'PAUSADO',
    continue: 'CONTINUAR',
    quit: 'SALIR',
    menuPlay: 'JUGAR',
    menuSettings: 'AJUSTES',
    menuAbout: 'ACERCA DE',
    menuInstructions: 'INSTRUCCIONES',
    menuBack: 'VOLVER',
    language: 'Idioma:',
    aboutSection: '\n[color=#FF6E31]Tubie Man[/color] wasn’t always trapped in a maze. A routine feeding-system calibration went spectacularly wrong, overloading a prototype power adapter and tearing a hole in the grid itself. Out rolled Tubie Man—bright orange, endlessly determined, and uniquely equipped with both an NG-tube and a G-tube to keep him going no matter what the maze throws at him.\n\nUnfortunately, [b]the maze isn’t empty[/b].\n\nFour anthropomorphic syringes now roam its corridors, each with their own idea of “[i]proper care[/i].”\n\n[color=#DE373A]Stingy[/color], the red enforcer, is fast, aggressive, and always closing in.\n\n[color=#55D400]Pokey[/color], green and persistent, means well but tends to get distracted—sometimes looping endlessly in circles.\n\n[color=#099EDE]Pricky[/color], a cerulean blue bundle of nerves, tries to chase but often forgets what he’s doing and wanders off instead.\n\nAnd [color=#FFB851]Doc[/color], orange like Tubie Man himself, appears only in the deeper levels, slowing down to think, stopping entirely, and then changing course when he decides he has a better plan.\n\nScattered throughout the maze are [b]nutrient pellets[/b] — tiny energy boosts Tubie Man must collect to survive. When he grabs one of the power-up band-aids tucked into the corners, things get intense. A sudden bout of catastrophic heartburn gives Tubie Man the ability to shoot fireballs for a short time, sending the syringes running for cover until the effect wears off. Pricky, especially terrified, may panic so badly he crashes into walls and stuns himself.\n\nAs the maze empties and most of the nutrients are gone, danger escalates. Stingy enters [b]Sterilization Mode[/b] — moving even faster and becoming completely immune to fireballs. Pokey grows more erratic. Pricky grows more [b]confused[/b]. Doc... keeps thinking...\n\n[size=18]Now Tubie Man races the clock, the maze, and his pursuers—proving he’s more than a patient. He’s a survivor. He’s a problem. And he’s not done yet.[/size]',
    instructionsSection: '\n[color=orange][size=18][b]Movement[/b][/size][/color]\n- Use [b][i]WASD[/b][/i], [b][i]arrow keys[/b][/i], or the [b][i]left stick[/b][/i] on a controller to move.\n\n[color=orange][size=18][b]Menus[/b][/size][/color]\n- Press [b][i]Enter[/b][/i] or [b][i]Space[/b][/i] to select a menu button.\n- Use [b][i]WASD[/b][/i], [b][i]arrow keys[/b][/i], [b][i]Tab, or the [b][i]left stick[/b][/i] to navigate menus.\n\n[color=orange][size=18][b]Pause[/b][/size][/color]\n- Press [b][i]Escape[/b][/i] (keyboard) or [b][i]Select/Share[/b][/i] (controller) to pause the game.\n\n[color=orange][size=18][b]Actions[/b][/size][/color]\n- Press [b][i]Space[/b][/i] (keyboard) or [b][i]A/X[/b][/i] (controller) to breathe fireballs.\n\n[color=orange][size=18][b]Scoring & Power-Ups[/b][/size][/color]\n- Collect nutrient pellets to score points.\n- Collect up to two bonuses per level for extra points.\n- Defeat enemies while powered up to earn points.\n- Eat the power-up in the corner to gain the ability to breathe fire.',
    helloWorld: 'Hola Mundo',
    menuHighScores: 'PUNTUACIONES',
    newHighScore: '¡NUEVA PUNTUACIÓN!',
    enterName: 'Ingresa Tu Nombre:',
    save: 'GUARDAR',
    rank: 'RANGO',
    name: 'NOMBRE',
    noScores: '¡Sin puntuaciones!',
    playAgain: 'JUGAR DE NUEVO',
    viewScores: 'VER PUNTUACIONES',
    settingFire: 'Fuego',
    settingContinue: 'Continuar',
    settingPause: 'Pausa',
    settingUp: 'Arriba',
    settingDown: 'Abajo',
    settingLeft: 'Izquierda',
    settingRight: 'Derecha',
    settingArcadeMode: 'Modo Arcade',
    on: 'SÍ',
    off: 'NO',
    tabGameplay: 'JUEGO',
    tabKeyboard: 'TECLADO',
    tabController: 'MANDO',
    getReady: '¡Prepárate!',
    settingMasterVolume: 'Volumen',
    settingMute: 'Silenciar',
    settingsSfxMute: 'Silenciar Sonidos',
    settingsMusicMute: 'Silenciar Música',
    settingMuteKey: 'Tecla Silencio',  
    isRightHanded: "Diseño táctil",
    rightHanded: "Diestro",
    leftHanded: "Zurdo",
    copyright: '©Tubie Tech 2026, All Rights Reserved'
  },
  [Language.FRENCH]: {
    gameTitle: 'Tubie-Man',
    gameOver: 'JEU TERMINÉ',
    clickToRestart: 'Cliquer pour Redémarrer',
    selectDifficulty: 'Difficulté:',
    easy: 'FACILE',
    medium: 'MOYEN',
    hard: 'DIFFICILE',
    controls: 'Contrôles: Flèches ou WASD\nFeu: ESPACE\nTactile: Glisser direction',
    score: 'Score',
    highScore: 'Meilleur',
    lives: 'Vies',
    level: 'Niveau',
    power: 'Pouvoir',
    powerReady: 'Prêt ',
    powerNone: 'Aucun',
    powerActive: 'Actif',
    paused: 'PAUSE',
    continue: 'CONTINUER',
    quit: 'QUITTER',
    menuPlay: 'JOUER',
    menuSettings: 'PARAMÈTRES',
    menuAbout: 'À PROPOS',
    menuInstructions: 'INSTRUCTIONS',
    menuBack: 'RETOUR',
    language: 'Langue:',
    aboutSection: '\n[color=#FF6E31]Tubie Man[/color] wasn’t always trapped in a maze. A routine feeding-system calibration went spectacularly wrong, overloading a prototype power adapter and tearing a hole in the grid itself. Out rolled Tubie Man—bright orange, endlessly determined, and uniquely equipped with both an NG-tube and a G-tube to keep him going no matter what the maze throws at him.\n\nUnfortunately, [b]the maze isn’t empty[/b].\n\nFour anthropomorphic syringes now roam its corridors, each with their own idea of “[i]proper care[/i].”\n\n[color=#DE373A]Stingy[/color], the red enforcer, is fast, aggressive, and always closing in.\n\n[color=#55D400]Pokey[/color], green and persistent, means well but tends to get distracted—sometimes looping endlessly in circles.\n\n[color=#099EDE]Pricky[/color], a cerulean blue bundle of nerves, tries to chase but often forgets what he’s doing and wanders off instead.\n\nAnd [color=#FFB851]Doc[/color], orange like Tubie Man himself, appears only in the deeper levels, slowing down to think, stopping entirely, and then changing course when he decides he has a better plan.\n\nScattered throughout the maze are [b]nutrient pellets[/b] — tiny energy boosts Tubie Man must collect to survive. When he grabs one of the power-up band-aids tucked into the corners, things get intense. A sudden bout of catastrophic heartburn gives Tubie Man the ability to shoot fireballs for a short time, sending the syringes running for cover until the effect wears off. Pricky, especially terrified, may panic so badly he crashes into walls and stuns himself.\n\nAs the maze empties and most of the nutrients are gone, danger escalates. Stingy enters [b]Sterilization Mode[/b] — moving even faster and becoming completely immune to fireballs. Pokey grows more erratic. Pricky grows more [b]confused[/b]. Doc... keeps thinking...\n\n[size=18]Now Tubie Man races the clock, the maze, and his pursuers—proving he’s more than a patient. He’s a survivor. He’s a problem. And he’s not done yet.[/size]',
    instructionsSection: '\n[color=orange][size=18][b]Movement[/b][/size][/color]\n- Use [b][i]WASD[/b][/i], [b][i]arrow keys[/b][/i], or the [b][i]left stick[/b][/i] on a controller to move.\n\n[color=orange][size=18][b]Menus[/b][/size][/color]\n- Press [b][i]Enter[/b][/i] or [b][i]Space[/b][/i] to select a menu button.\n- Use [b][i]WASD[/b][/i], [b][i]arrow keys[/b][/i], [b][i]Tab, or the [b][i]left stick[/b][/i] to navigate menus.\n\n[color=orange][size=18][b]Pause[/b][/size][/color]\n- Press [b][i]Escape[/b][/i] (keyboard) or [b][i]Select/Share[/b][/i] (controller) to pause the game.\n\n[color=orange][size=18][b]Actions[/b][/size][/color]\n- Press [b][i]Space[/b][/i] (keyboard) or [b][i]A/X[/b][/i] (controller) to breathe fireballs.\n\n[color=orange][size=18][b]Scoring & Power-Ups[/b][/size][/color]\n- Collect nutrient pellets to score points.\n- Collect up to two bonuses per level for extra points.\n- Defeat enemies while powered up to earn points.\n- Eat the power-up in the corner to gain the ability to breathe fire.',
    helloWorld: 'Bonjour le Monde',
    menuHighScores: 'MEILLEURS SCORES',
    newHighScore: 'NOUVEAU RECORD!',
    enterName: 'Entrez Votre Nom:',
    save: 'SAUVER',
    rank: 'RANG',
    name: 'NOM',
    noScores: 'Pas de scores!',
    playAgain: 'REJOUER',
    viewScores: 'VOIR SCORES',
    settingFire: 'Feu',
    settingContinue: 'Continuer',
    settingPause: 'Pause',
    settingUp: 'Haut',
    settingDown: 'Bas',
    settingLeft: 'Gauche',
    settingRight: 'Droite',
    settingArcadeMode: 'Mode Arcade',
    on: 'OUI',
    off: 'NON',
    tabGameplay: 'JEU',
    tabKeyboard: 'CLAVIER',
    tabController: 'MANETTE',
    getReady: 'Préparez-vous!',
    settingMasterVolume: 'Volume',
    settingMute: 'Muet',
    settingsSfxMute: 'Couper les Sons',
    settingsMusicMute: 'Couper la Musique',
    settingMuteKey: 'Touche Muet',  
    isRightHanded: "Disposition tactile",
    rightHanded: "Droitier",
    leftHanded: "Gaucher",
    copyright: '©Tubie Tech 2026, All Rights Reserved'
  },
  [Language.GERMAN]: {
    gameTitle: 'Tubie-Man',
    gameOver: 'SPIEL VORBEI',
    clickToRestart: 'Klicken zum Neustarten',
    selectDifficulty: 'Schwierigkeit:',
    easy: 'LEICHT',
    medium: 'MITTEL',
    hard: 'SCHWER',
    controls: 'Steuerung: Pfeile oder WASD\nFeuer: LEERTASTE\nTouch: Richtung wischen',
    score: 'Punkte',
    highScore: 'Rekord',
    lives: 'Leben',
    level: 'Level',
    power: 'Kraft',
    powerReady: 'Bereit',
    powerNone: 'Keine',
    powerActive: 'Aktiv ',
    paused: 'PAUSIERT',
    continue: 'FORTSETZEN',
    quit: 'BEENDEN',
    menuPlay: 'SPIELEN',
    menuSettings: 'EINSTELLUNGEN',
    menuAbout: 'ÜBER',
    menuInstructions: 'ANLEITUNG',
    menuBack: 'ZURÜCK',
    language: 'Sprache:',
    aboutSection: '\n[color=#FF6E31]Tubie Man[/color] wasn’t always trapped in a maze. A routine feeding-system calibration went spectacularly wrong, overloading a prototype power adapter and tearing a hole in the grid itself. Out rolled Tubie Man—bright orange, endlessly determined, and uniquely equipped with both an NG-tube and a G-tube to keep him going no matter what the maze throws at him.\n\nUnfortunately, [b]the maze isn’t empty[/b].\n\nFour anthropomorphic syringes now roam its corridors, each with their own idea of “[i]proper care[/i].”\n\n[color=#DE373A]Stingy[/color], the red enforcer, is fast, aggressive, and always closing in.\n\n[color=#55D400]Pokey[/color], green and persistent, means well but tends to get distracted—sometimes looping endlessly in circles.\n\n[color=#099EDE]Pricky[/color], a cerulean blue bundle of nerves, tries to chase but often forgets what he’s doing and wanders off instead.\n\nAnd [color=#FFB851]Doc[/color], orange like Tubie Man himself, appears only in the deeper levels, slowing down to think, stopping entirely, and then changing course when he decides he has a better plan.\n\nScattered throughout the maze are [b]nutrient pellets[/b] — tiny energy boosts Tubie Man must collect to survive. When he grabs one of the power-up band-aids tucked into the corners, things get intense. A sudden bout of catastrophic heartburn gives Tubie Man the ability to shoot fireballs for a short time, sending the syringes running for cover until the effect wears off. Pricky, especially terrified, may panic so badly he crashes into walls and stuns himself.\n\nAs the maze empties and most of the nutrients are gone, danger escalates. Stingy enters [b]Sterilization Mode[/b] — moving even faster and becoming completely immune to fireballs. Pokey grows more erratic. Pricky grows more [b]confused[/b]. Doc... keeps thinking...\n\n[size=18]Now Tubie Man races the clock, the maze, and his pursuers—proving he’s more than a patient. He’s a survivor. He’s a problem. And he’s not done yet.[/size]',
    instructionsSection: '\n[color=orange][size=18][b]Movement[/b][/size][/color]\n- Use [b][i]WASD[/b][/i], [b][i]arrow keys[/b][/i], or the [b][i]left stick[/b][/i] on a controller to move.\n\n[color=orange][size=18][b]Menus[/b][/size][/color]\n- Press [b][i]Enter[/b][/i] or [b][i]Space[/b][/i] to select a menu button.\n- Use [b][i]WASD[/b][/i], [b][i]arrow keys[/b][/i], [b][i]Tab, or the [b][i]left stick[/b][/i] to navigate menus.\n\n[color=orange][size=18][b]Pause[/b][/size][/color]\n- Press [b][i]Escape[/b][/i] (keyboard) or [b][i]Select/Share[/b][/i] (controller) to pause the game.\n\n[color=orange][size=18][b]Actions[/b][/size][/color]\n- Press [b][i]Space[/b][/i] (keyboard) or [b][i]A/X[/b][/i] (controller) to breathe fireballs.\n\n[color=orange][size=18][b]Scoring & Power-Ups[/b][/size][/color]\n- Collect nutrient pellets to score points.\n- Collect up to two bonuses per level for extra points.\n- Defeat enemies while powered up to earn points.\n- Eat the power-up in the corner to gain the ability to breathe fire.',
    helloWorld: 'Hallo Welt',
    menuHighScores: 'BESTENLISTE',
    newHighScore: 'NEUER HIGHSCORE!',
    enterName: 'Gib Deinen Namen Ein:',
    save: 'SPEICHERN',
    rank: 'RANG',
    name: 'NAME',
    noScores: 'Noch keine Punkte!',
    playAgain: 'NOCHMAL SPIELEN',
    viewScores: 'PUNKTE ANSEHEN',
    settingFire: 'Feuer',
    settingContinue: 'Weiter',
    settingPause: 'Pause',
    settingUp: 'Hoch',
    settingDown: 'Runter',
    settingLeft: 'Links',
    settingRight: 'Rechts',
    settingArcadeMode: 'Arcade-Modus',
    on: 'AN',
    off: 'AUS',
    tabGameplay: 'SPIEL',
    tabKeyboard: 'TASTATUR',
    tabController: 'CONTROLLER',
    getReady: 'Mach dich bereit!',
    settingMasterVolume: 'Lautstärke',
    settingMute: 'Stumm',
    settingsSfxMute: 'Töne Stumm',
    settingsMusicMute: 'Musik Stumm',
    settingMuteKey: 'Stumm-Taste',
    isRightHanded: "Touch-Layout",
    rightHanded: "Rechts",
    leftHanded: "Links",
    copyright: '©Tubie Tech 2026, All Rights Reserved'
  }
};

export type LanguageKey = keyof typeof languageFiles[Language.ENGLISH];